### PR TITLE
V0.0.9 Beta

### PR DESCRIPTION
**Pull request by hankjacobs**
Tracking v0.0.8 release

### CODE REVIEW

**Comment by tootedom** [comment]
Hola,

Just to let you know (incase the comment is missed - not sure how to reopen closed issue - https://github.com/dollarshaveclub/cloudworker/issues/25)

The adding of the blank `transfer-encoding` header is causing fetching from upstreams (S3, Google, to fail).

Removing this line worked locally for me, but I'm unsure of the background surrounding the addition of this header here.

https://github.com/dollarshaveclub/cloudworker/blob/master/lib/runtime/fetch.js#L15

Hope that helps you out.  Many thanks (thanks for this repo in first place)
Cheers
/dom

**Comment by hankjacobs** [comment]
@tootedom Thanks for catching that. There is some context around setting that header to an empty string (it removes it). It was an attempt to prevent that header from being added in unnecessary scenarios.

 How large is the file you’re POSTing to S3? Can you share the file and your worker script?

**Comment by hankjacobs** [comment]
I’ve reopened #25. Let’s discuss there. Thanks.

**Comment by hankjacobs** [comment]
Closes #40

**Comment by hankjacobs** [comment]
v0.0.8 is already in use in npm (my bad). Using version 0.0.9

**Pull request merged**
